/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Thu Sep 04 2025 17:08:35 GMT-0500 (Central Daylight Time).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'reactflow/bundles/FlowClassDiagramWidget.bundle',
    './FlowClassDiagramControl',
    'css!reactflow/bundles/styles/FlowClassDiagramWidget.bundle.css'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    FlowClassDiagramWidget,
    FlowClassDiagramControl
) {
    'use strict';

    function FlowClassDiagramPanel(layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'FlowClassDiagramPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this.appId = `FlowClassDiagram`;

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    }

    //inherit from PanelBaseWithHeader
    _.extend(FlowClassDiagramPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(FlowClassDiagramPanel.prototype, IActivePanel.prototype);

    FlowClassDiagramPanel.prototype._initialize = function () {
        var self = this;

        this.$el.prop('id', this.appId);
        this.$el.css({
            width: '100%',
            height: '100%',
        });

        // //set Widget title
        // this.setTitle('');

        // this.widget = new FlowClassDiagramWidget(this.logger, this.$el);

        // this.widget.setTitle = function (title) {
        //     self.setTitle(title);
        // };

        this.control = new FlowClassDiagramControl({
            logger: this.logger,
            client: this._client,
            widget: {}
        });

        this.onActivate();
    };

    FlowClassDiagramPanel.prototype.afterAppend = function afterAppend() {
        FlowClassDiagramWidget(this.appId, this.control, this);
    };
    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    FlowClassDiagramPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };

    FlowClassDiagramPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
        // this.widget.onWidgetContainerResize(width, height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    FlowClassDiagramPanel.prototype.destroy = function () {
        this.control.destroy();
        // this.widget.destroy();

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    FlowClassDiagramPanel.prototype.onActivate = function () {
        // this.widget.onActivate();
        this.control.onActivate();
        // WebGMEGlobal.KeyboardManager.setListener(this.widget);
        WebGMEGlobal.Toolbar.refresh();
    };

    FlowClassDiagramPanel.prototype.onDeactivate = function () {
        // this.widget.onDeactivate();
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return FlowClassDiagramPanel;
});
