/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Sep 10 2025 11:05:19 GMT-0500 (Central Daylight Time).
 */

define([
    'js/PanelBase/PanelBaseWithHeader',
    'js/PanelManager/IActivePanel',
    'reactflow/bundles/FlowListWidget.bundle',
    './FlowListControl'
], function (
    PanelBaseWithHeader,
    IActivePanel,
    FlowListWidget,
    FlowListControl
) {
    'use strict';

    function FlowListPanel(layoutManager, params) {
        var options = {};
        //set properties from options
        options[PanelBaseWithHeader.OPTIONS.LOGGER_INSTANCE_NAME] = 'FlowListPanel';
        options[PanelBaseWithHeader.OPTIONS.FLOATING_TITLE] = true;

        //call parent's constructor
        PanelBaseWithHeader.apply(this, [options, layoutManager]);

        this._client = params.client;
        this.appId = `FlowList`;

        //initialize UI
        this._initialize();

        this.logger.debug('ctor finished');
    }

    //inherit from PanelBaseWithHeader
    _.extend(FlowListPanel.prototype, PanelBaseWithHeader.prototype);
    _.extend(FlowListPanel.prototype, IActivePanel.prototype);

    FlowListPanel.prototype._initialize = function () {
        var self = this;

        this.$el.prop('id', this.appId);
        this.$el.css({
            width: '100%',
            height: '100%',
        });

        this.control = new FlowListControl({
            logger: this.logger,
            client: this._client
        });

        this.onActivate();
    };

    FlowListPanel.prototype.afterAppend = function afterAppend() {
        FlowListWidget(this.appId, this.control, this);
    };

    /* OVERRIDE FROM WIDGET-WITH-HEADER */
    /* METHOD CALLED WHEN THE WIDGET'S READ-ONLY PROPERTY CHANGES */
    FlowListPanel.prototype.onReadOnlyChanged = function (isReadOnly) {
        //apply parent's onReadOnlyChanged
        PanelBaseWithHeader.prototype.onReadOnlyChanged.call(this, isReadOnly);

    };

    FlowListPanel.prototype.onResize = function (width, height) {
        this.logger.debug('onResize --> width: ' + width + ', height: ' + height);
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    FlowListPanel.prototype.destroy = function () {
        this.control.destroy();
        

        PanelBaseWithHeader.prototype.destroy.call(this);
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    FlowListPanel.prototype.onActivate = function () {
        this.control.onActivate();
        WebGMEGlobal.Toolbar.refresh();
    };

    FlowListPanel.prototype.onDeactivate = function () {
        this.control.onDeactivate();
        WebGMEGlobal.KeyboardManager.setListener(undefined);
        WebGMEGlobal.Toolbar.refresh();
    };

    return FlowListPanel;
});
